# Generated by Django 4.1.7 on 2023-03-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_alter_student_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
