# Generated by Django 4.1.7 on 2023-03-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_theme_course_task_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
