# Generated by Django 4.1.7 on 2023-03-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
