# Generated by Django 4.1.2 on 2023-03-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_solution_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
